In [1]:
import scipy.io

In [2]:
import scipy.io

battery = scipy.io.loadmat(
    "../data/NASA/5. Battery Data Set/1. BatteryAgingARC-FY08Q4/B0005.mat"
)

In [3]:
battery.keys()

dict_keys(['__header__', '__version__', '__globals__', 'B0005'])

In [4]:
#MATLAB 구조체라서 1,1, 원래는 행열
battery["B0005"].shape

(1, 1)

In [5]:
#numpy 배열 형태
type(battery["B0005"])

numpy.ndarray

In [6]:
# 배열 안에 데이터 확인
battery["B0005"].dtype

dtype([('cycle', 'O')])

In [8]:
cycle = battery["B0005"]["cycle"][0,0]

In [9]:
type(cycle)

numpy.ndarray

In [10]:
len(cycle)

1

In [ ]:
#cycle마다 작업타입(충방전), 실험실 온도, 날짜, 데이터
cycle[0].dtype

dtype([('type', 'O'), ('ambient_temperature', 'O'), ('time', 'O'), ('data', 'O')])

In [ ]:
#616개의 cycle이 1차원 배열에 저장
cycle[0].shape

(616,)

In [16]:
len(cycle[0])

616

In [24]:
#616개 중 첫 번째 기록
record = cycle[0][0]
record["type"]

array(['charge'], dtype='<U6')

In [25]:
record.dtype

dtype([('type', 'O'), ('ambient_temperature', 'O'), ('time', 'O'), ('data', 'O')])

In [26]:
record["data"].dtype

dtype([('Voltage_measured', 'O'), ('Current_measured', 'O'), ('Temperature_measured', 'O'), ('Current_charge', 'O'), ('Voltage_charge', 'O'), ('Time', 'O')])

In [ ]:
data = record["data"][0,0]

In [40]:
#dtype->이름->구조체, dtype-> float64->행렬
voltage = data["Voltage_measured"]
type(voltage)

numpy.ndarray

In [41]:
voltage.shape

(1, 789)

In [42]:
#flatten: (1,789)행렬->(789,)1차원 배열로 
voltage = data["Voltage_measured"].flatten()

current = data["Current_measured"].flatten()

temperature = data["Temperature_measured"].flatten()

time = data["Time"].flatten()

In [43]:
voltage.shape

(789,)

In [44]:
#DataFrame 생성
import pandas as pd

df_charge = pd.DataFrame({
    "Voltage": voltage,
    "Current": current,
    "Temperature": temperature,
    "Time": time
})

In [45]:
df_charge.head()

    Voltage   Current  Temperature    Time
0  3.873017 -0.001201    24.655358   0.000
1  3.479394 -4.030268    24.666480   2.532
2  4.000588  1.512731    24.675394   5.500
3  4.012395  1.509063    24.693865   8.344
4  4.019708  1.511318    24.705069  11.125

In [46]:
df_charge.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 789 entries, 0 to 788
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Voltage      789 non-null    float64
 1   Current      789 non-null    float64
 2   Temperature  789 non-null    float64
 3   Time         789 non-null    float64
dtypes: float64(4)
memory usage: 24.8 KB

In [48]:
df_charge.describe()

          Voltage     Current  Temperature         Time
count  789.000000  789.000000   789.000000   789.000000
mean     4.187420    0.643455    25.324079  2725.952433
std      0.045794    0.625804     1.011951  2233.400767
min      3.479394   -4.030268    24.167062     0.000000
25%      4.190885    0.084497    24.404019   702.500000
50%      4.205710    0.387115    25.060947  2177.047000
75%      4.206481    1.496159    26.056859  4467.703000
max      4.209949    1.514393    27.445134  7597.875000